coverage:
  status:
    project:
      default:
        target: 85%
        threshold: 1%
    patch:
      default:
        target: 80%
comment:
  layout: "reach, diff, files"
  behavior: default
flags:
  agenix:
    paths: [packages/agenix/]
  agenix_firebase:
    paths: [packages/agenix_firebase/]
