name: agenix
description: "A framework that lets you build AI agents in Flutter that actually use tools, remember context, and talk to each other. No backend required."
version: 4.1.0
homepage: https://github.com/ahmadexe/agenix
repository: https://github.com/ahmadexe/agenix/tree/main/packages/agenix

resolution: workspace

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

keywords:
  - flutter
  - ai
  - prompt
  - gemini
  - tools
  - llm
  - agentic

dependencies:
  flutter:
    sdk: flutter
  google_generative_ai: ^0.4.7
  uuid: ^4.5.1
  dio: ^5.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ">=5.0.0 <7.0.0"
  mocktail: ^1.0.4

flutter:
