// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApo3Y7il06NbItcDi8eg_vDJ7bcb6kJLs',
    appId: '1:296327160947:web:4c6bcb4cba99861012b606',
    messagingSenderId: '296327160947',
    projectId: 'agenix-test',
    authDomain: 'agenix-test.firebaseapp.com',
    storageBucket: 'agenix-test.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACccZhGDdewfPYxbnFOTEvxPRK9hdxQzY',
    appId: '1:296327160947:android:18df36606eea95da12b606',
    messagingSenderId: '296327160947',
    projectId: 'agenix-test',
    storageBucket: 'agenix-test.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAR-otPqCYYXitdYJFNr1gq7fVq7Uu3y2A',
    appId: '1:296327160947:ios:9688df7c4dc6aead12b606',
    messagingSenderId: '296327160947',
    projectId: 'agenix-test',
    storageBucket: 'agenix-test.firebasestorage.app',
    iosBundleId: 'com.example.basicApp',
  );
}
